# Generated by Django 4.2.27 on 2026-01-16 12:18

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Index of this chunk within the document (0-based)"
                    ),
                ),
                ("text", models.TextField(help_text="The text content of this chunk")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=768,
                        help_text="Vector embedding from Ollama nomic-embed-text",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The source document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="docs.document",
                    ),
                ),
            ],
            options={
                "db_table": "doc_chunks",
                "ordering": ["document", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="doc_chunks_documen_44f820_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="documentchunk",
            constraint=models.UniqueConstraint(
                fields=("document", "chunk_index"), name="unique_document_chunk"
            ),
        ),
    ]
